### ISSUE TITLE
windows create file parameters

### ISSUE THREAD

**Issue by jowasp** [zscproject/OWASP-ZSC#100]
the option [+] windows_x86/create_file/ 
parameters filename is clear but how should this content be provided?

**Comment by Ali-Razmjoo** [comment]
Hi Johanna,
```
[!] create_file('filename','content')
[+] windows_x86/create_file/none
[+] windows_x86/create_file/xor_random
[+] windows_x86/create_file/add_random
[+] windows_x86/create_file/sub_random
[+] windows_x86/create_file/xor_yourvalue
```
so it's must be `zsc -p windows_x86/create_file/none -i "johanna.txt~~~whatsup"`, and output of this command:

`\x31\xc9\x64\x8b\x41\x30\x8b\x40\x0c\x8b\x70\x14\xad\x96\xad\x8b\x58\x10\x8b\x53\x3c\x01\xda\x8b\x52\x78\x01\xda\x8b\x72\x20\x01\xde\x31\xc9\x41\xad\x01\xd8\x81\x38\x47\x65\x74\x50\x75\xf4\x81\x78\x04\x72\x6f\x63\x41\x75\xeb\x81\x78\x08\x64\x64\x72\x65\x75\xe2\x8b\x72\x24\x01\xde\x66\x8b\x0c\x4e\x49\x8b\x72\x1c\x01\xde\x8b\x14\x8e\x01\xda\x31\xf6\x89\xd6\x31\xc9\x51\x68\x61\x72\x79\x41\x68\x4c\x69\x62\x72\x68\x4c\x6f\x61\x64\x54\x53\xff\xd2\x31\xc9\x66\xb9\x6c\x6c\x51\x68\x72\x74\x2e\x64\x68\x6d\x73\x76\x63\x54\xff\xd0\x31\xff\x89\xc7\x31\xd2\x52\x66\xba\x65\x6d\x52\x68\x73\x79\x73\x74\x89\xe1\x51\x57\x31\xd2\x89\xf2\xff\xd2\x31\xc9\x68\x2e\x74\x78\x74\x68\x61\x6e\x6e\x61\x68\x3e\x6a\x6f\x68\x68\x74\x73\x75\x70\x68\x20\x77\x68\x61\x68\x65\x63\x68\x6f\x54\xff\xd0\x31\xd2\x52\x68\x65\x78\x69\x74\x89\xe1\x51\x57\xff\xd6\x31\xc9\x51\xff\xd0`

anything else?

**Comment by jowasp** [comment]
Does that work with all kind of files? I mean...pdf, .php etc?

**Comment by Ali-Razmjoo** [comment]
it's shouldn't has any problem! I mean it's just getting filename and content, both could be anything, right ?

**Comment by jowasp** [comment]
I'll test with PDF and asp or php files ;-)

**Comment by Ali-Razmjoo** [comment]
cool, thank you.
