### ISSUE TITLE
menu obfuscate module filename

### ISSUE THREAD

**Issue by jowasp** [zscproject/OWASP-ZSC#106]
I get the following issue when using the obfuscate module:

I use tab, I get 'simple_' as menu, when enter it gives me the error 'please enter a valid code name'

```
encode> simple_
[!] please enter a valid encode name
```

The menu shows this:
```
encode> simple_
simple_base64_rev  simple_hex         simple_hex_rev  
```

**Comment by Ali-Razmjoo** [comment]
Hi Johanna, 

It's because of `simple_` exist in all encodes name and they have difference in the after of `simple_` so you need to time and other char, example `simple_b` and push tab again, it will autocomplete for you.
