### ISSUE TITLE
shell-storm download mangles quotes

### ISSUE THREAD

**Issue by sizzop** [zscproject/OWASP-ZSC#111]
shell-storm payloads display with quotes (") changed to the HTML escaped version (&amp;quot;). I have not checked every shell-storm payload, but the ones I have checked all show this happening.

    BRIBEA-COTP-1:OWASP-ZSC brianbeaudry$ python zsc.py --shell-storm download 73 | tail -n 15
    char main[]=
    &quot;\x31\xc0\x31\xdb\x31\xc9\x31\xd2&quot;
    &quot;\xeb\x32\x5b\xb0\x05\x31\xc9\xcd&quot;
    &quot;\x80\x89\xc6\xeb\x06\xb0\x01\x31&quot;
    &quot;\xdb\xcd\x80\x89\xf3\xb0\x03\x83&quot;
    &quot;\xec\x01\x8d\x0c\x24\xb2\x01\xcd&quot;
    &quot;\x80\x31\xdb\x39\xc3\x74\xe6\xb0&quot;
    &quot;\x04\xb3\x01\xb2\x01\xcd\x80\x83&quot;
    &quot;\xc4\x01\xeb\xdf\xe8\xc9\xff\xff&quot;
    &quot;\xff&quot;
    &quot;/etc/passwd&quot;; //Put here the file path, default is /etc/passwd
    
    BRIBEA-COTP-1:OWASP-ZSC brianbeaudry$

**Comment by sizzop** [comment]
I pushed some code to fix this however I did not test on python 3. If somebody could verify that the solution works with py3 that would be great!

**Comment by Ali-Razmjoo** [comment]
Hi Brian, I've tested it on python3, it's fixed, thank you.
