### ISSUE TITLE
OWASP Code Sprint 2017

### ISSUE THREAD

**Issue by jajodiaraghav** [zscproject/OWASP-ZSC#118]
Hello
I am Raghav Jajodia, an Engineering undergrad from India and I am really interested in spending my summer working on the idea titled "OWASP ZSC".

I have been working as a web, mobile and desktop application developer for the past two years and have good experience with python, flask and django. I also have a good amount of Open source experience and have made substantial contributions to various projects. I also fulfill all the knowledge prerequisites mentioned. I would be grateful if you could answer my queries:

- How should I get started?
- What exactly is the project about?
- Should I start working on my proposal?

Link to my github: https://github.com/jajodiaraghav

Thanks
@Pratik151

**Comment by Ali-Razmjoo** [comment]
Hello @jajodiaraghav , 

You can start from reading documents in [here](https://www.gitbook.com/book/ali-razmjoo/owasp-zsc/details). also, check out the developers' sections.
