### ISSUE TITLE
[Important] Add `Back` command

### ISSUE THREAD

**Issue by CodeMaxx** [zscproject/OWASP-ZSC#59]
Add `back` command to go back one step. It is very frustrating to restart from the beginning.

**Comment by Ali-Razmjoo** [comment]
that's true, we need to add `back` command, Working on it.

**Comment by CodeMaxx** [comment]
@Ali-Razmjoo Did you start working on this? Otherwise I was thinking of doing this today.

**Comment by Ali-Razmjoo** [comment]
Yes, I'm busy these days, Please contribute if you've free time. thanks.
