### ISSUE TITLE
Bug in windows opcoder

### ISSUE THREAD

**Issue by CodeMaxx** [zscproject/OWASP-ZSC#65]
Only one of [line 15](https://github.com/zscproject/OWASP-ZSC/blob/master/lib/opcoder/windows.py#L15) and [line 63](https://github.com/zscproject/OWASP-ZSC/blob/master/lib/opcoder/windows.py#L63) can be correct. 
@Pratik151 @Ali-Razmjoo

**Comment by Pratik151** [comment]
@CodeMaxx  line 63 is correct. you can remove line 15 one. Make PR if you want as you reported :) or I will make PR if you can't. Remove it for linux opcoder also.

**Comment by Ali-Razmjoo** [comment]
@CodeMaxx Thanks for your report, @Pratik151 yes that's correct, opcode of `pop %eax` must be `58`.

**Comment by Ali-Razmjoo** [comment]
@Pratik151 Please send the fixation. thanks.

**Comment by Pratik151** [comment]
@Ali-Razmjoo  I asked Akash if he wants to do it as he reported it :P and he said that he will do it yesterday. I will ask him if he has done or I will make PR

**Comment by Ali-Razmjoo** [comment]
Thanks, merged.
