### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by CodeMaxx** [zscproject/OWASP-ZSC#75]
Continuous Integration is very useful for project development. Please go through this blog post 

[Why use Continuous Integration](https://about.gitlab.com/2015/02/03/7-reasons-why-you-should-be-using-ci/)

**Comment by Ali-Razmjoo** [comment]
Thanks Akash, I will take a look.

**Comment by CodeMaxx** [comment]
@Ali-Razmjoo If you decide to add Continuous Integration, reopen this issue so we can start working on it.

**Comment by Ali-Razmjoo** [comment]
Yes I would like to start it but we need to hold it, and just trying to fix the bugs first, we don't have much time to develop more. I think we need to leave it for after demo labs, we need a stable version for @jowasp  presenting.
