### ISSUE TITLE
mailing list / contact us Now info not correct 

### ISSUE THREAD

**Issue by jowasp** [zscproject/OWASP-ZSC#82]
The following info is not correct 

`Mailing List: https://lists.owasp.org/mailman/listinfo/owasp-zsc-tool-project`
`Contact US Now: owasp-zsc-tool-project[at]lists[dot]owasp[dot]org`
Please set the google user group since we don't maintain access to the mailing list at OWASP

**Comment by Ali-Razmjoo** [comment]
Thanks Johanna.
